### ISSUE TITLE
How to use/create hooks

### ISSUE THREAD

**Issue by MichalS16** [MichalS16/Git-hooks#4]

**Comment by MichalS16** [comment]
+ udělat example

**Comment by MichalS16** [comment]
napadlo mě to udělat jako jupyter notebook, kde bychom vymysleli nějaké příklady užitečných hooků.

**Comment by mrkoubek** [comment]
Supr, připravil jsem na to branche, můžeš zkusit třeba nějaký příklad toho pre-commit, a já kouknu na post-commit.

main
  └─ hooks-examples
      ├─ pre-commit
      └─ post-commit

**Comment by MichalS16** [comment]
Hele, mně se to branchové dělení na jednotlivé use casy nezdá jako zrovna elegantní nápad. Že defakto ty branche jsou na 99 % stejné, jen by se lišili v jednom souboru. Možná by to mělo účel, kdyby to mělo nějaký script pro jednotlivé githook, což nevím, jestli máš v plánu dělat.
Tak se přikláním spíš udělat ten notebook s ukázkou různých git-hooků

**Comment by mrkoubek** [comment]
Jasný no, co to vzít trochu jako cvičení, pro mě je to docela fajn si vyzkoušet víc práci s branches/merge strukturou, i když se budou lišit jen v pár souborech, aspoň tam nebude tolik konfliktů.) Můžu si zkoušet vyvíjen post-commit kapitolu/soubory zvlášť, aniž by se ti v jiných branches spouštěly moje zkušební post-commit skript pokusy 🦖

**Comment by MichalS16** [comment]
Jasný, já jsem to prvně špatně pochopil a nejdřív jsem psal a pak až přemýšlel :D. Promiň!
Na ty editační věci, je to super rozčlenění. Já jsem se prvně leknul, že to myslíš tak, že pro každý hook bude jedna větev ve finální verzi.

**Comment by mrkoubek** [comment]
No nějak to ještě upravíme, asi jsem to tím vskutku zkomplikoval, teď jsem zkoušel merge toho Jupyter souboru mezi branches, a i když to byl jediný konflikt, tak to není vůbec zábava mergovat Jupyter buňky, VSCode si s tím nějak neuměl úplně poradit automaticky. Takže možná ten examples.ipynb upravovat jen v hooks-examples branch, a pak mít případně další experimentální branches pro hook skripty.. uvidíme.)

**Comment by mrkoubek** [comment]
Ve finální verzi bych si představoval mít všechny side branches uzavřený, merged to main. Všechny hooks by pak byly v main, až budou hotový. 🐤
